/* Copyright (C) YOOtheme GmbH, https://www.gnu.org/licenses/gpl.html GNU/GPL */

function selectZooItem(i,s,o){jQuery("#"+o+"_id").val(i),jQuery("#"+o+"_name").val(s),window.bootstrap?Joomla.Modal.current.close():jModalClose()}(function(i){var s=function(){};i.extend(s.prototype,{name:"ZooApplication",options:{url:null,msgSelectItem:"Select Item"},initialize:function(e,t){this.options=i.extend({},this.options,t);var a=this;this.input=e,this.app=e.find("select.application"),this.categories=e.find("div.categories"),this.types=e.find("div.types"),this.item=e.find("div.item");var n=e.find("select.mode");n.length?(this.mode=n.val(),n.on("change",function(){a.mode=n.val(),a.setValues()})):this.categories.length?this.mode="categories":this.types.length?this.mode="types":this.item.length&&(this.mode="item"),this.setValues(),this.app.on("change",function(){a.setValues(),a.item.length&&(a.item.find("input:hidden").val(""),a.item.find("input:text").val(a.options.msgSelectItem))}),e.on("change","select",function(){i(this).closest("div.content").css("height","")}),i(e.closest("form")).find("input[id$=mode]:hidden, input[id$=params_type]:hidden, input[id$=params_category]:hidden, input[id$=params_item_id]:hidden").each(function(){i(this).closest(".control-group").remove().end().remove()}),window.bootstrap&&e.on("click",".item",function(d){d.preventDefault(),o(d.currentTarget.querySelector("a"))})},setValues:function(){var e=this.app.val();this.categories.length&&(e&&this.mode=="categories"?this.categories.removeClass("hidden"):this.categories.addClass("hidden"),this.input.find("select.category").each(function(){var t=i(this);t.hasClass("app-"+e)?t.removeClass("hidden").attr("name",t.data("category")).next(".chzn-container").removeClass("hidden"):t.addClass("hidden").attr("name","").next(".chzn-container").addClass("hidden")})),this.types.length&&(e&&this.mode=="types"?this.types.removeClass("hidden"):this.types.addClass("hidden"),this.input.find("select.type").each(function(){var t=i(this);t.hasClass("app-"+e)?t.removeClass("hidden").attr("name",t.data("type")).next(".chzn-container").removeClass("hidden"):t.addClass("hidden").attr("name","").next(".chzn-container").addClass("hidden")})),this.item.length&&(e&&this.mode=="item"?this.item.removeClass("hidden"):this.item.addClass("hidden"),this.item.find("a").attr("href",this.options.url+"&app_id="+e))}});function o(e){var t=i(`<div tabindex="-1" class="joomla-modal modal fade" aria-modal="true" role="dialog">
<div class="modal-dialog modal-lg jviewport-width80">
<div class="modal-content">
<div class="modal-header">
<h3 class="modal-title">Choose Item</h3>
</div>
<div class="modal-body jviewport-height60"><iframe class="iframe" src="`+e+`" name="Change Image" height="100%" width="100%"></iframe>
</div>
</div>
</div>`).appendTo("body")[0];Joomla.initialiseModal(t,{isJoomla:!0}),t.addEventListener("hidden.bs.modal",function(a){i(t).remove()}),t.open()}i.fn[s.prototype.name]=function(){var e=arguments,t=e[0]?e[0]:null;return this.each(function(){var a=i(this);if(s.prototype[t]&&a.data(s.prototype.name)&&t!="initialize")a.data(s.prototype.name)[t].apply(a.data(s.prototype.name),Array.prototype.slice.call(e,1));else if(!t||i.isPlainObject(t)){var n=new s;s.prototype.initialize&&n.initialize.apply(n,i.merge([a],e)),a.data(s.prototype.name,n)}else i.error("Method "+t+" does not exist on jQuery."+s.name)})}})(jQuery);
